spring:
  # 로그파일 설정
  application:
    name:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  redis:
    host:
    port:
    password:

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

# sms
accessKey:
secretKey:
serviceId:

# system number
systemPhoneNumber:
# jwt
jwt:
  secret:
    key:
# firebase
fcm:
  certification:
